server.port=8080
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=attendance;encrypt=true;trustServerCertificate=true;integratedSecurity=true;
spring.jdbc.template.show-sql=true